// @flow

let {describe, it} = global;

import expect from 'expect';
import {
  validatePlants,
  validatePlantDetail,
  validatePlantingInformation,
  validatePlantPhotos,
} from '../Plant';

let examplePlant = {
  result: 'sukses',
  message: [
    {
      id: 3263,
      user_id: 1721,
      plant_id: 6,
      date: '2016-11-09',
      area: 500,
      unit: 'm2',
      desc: 'Lelelel',
      province: 16,
      city: 271,
      subdistrict: 4019,
      village: 50135,
      foto: 'http://ingkarsa.com/uploads/qarsa/plants/image1478847424.jpg',
      foto_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1478847424.jpg',
      cropping_system: 'Lahan',
      seed_id: null,
      watering: null,
      type_land: null,
      fertility: null,
      using_persemian: null,
      height_land: 'tinggi',
      longitude: '0',
      latitude: '0',
      created_at: '2016-11-11 12:22:08',
      updated_at: '2016-11-11 13:57:04',
      plant_category_id: 19,
      plant_varieties_id: 799,
      status: '1',
      soil_ph: '7,5-8,5',
      plant_fase: 'Pengolahan Lahan',
      plant_address_gps: 'Tidak bisa mendeteksi lokasi',
      is_temporary_variety: false,
      temp_fase: 'Pengolahan Lahan dan Persemaian',
      type: null,
      plant_category_name: 'Kentang',
      plant_varieties_name: 'Medians',
      province_name: 'Banten',
      city_name: 'Kota Tangerang Selatan',
      subdistrict_name: ' Serpong Utara',
      village_name: 'Pakulonan',
      plant_name: 'Kentang',
      seed_name: null,
      disclaimer: 'Data merupakan estimasi',
      age_plant: '2 hari',
      estimate: '01 January 1970',
      potential: '1.25 ton',
      reaction: 'Agak Basa',
      dolomit: '0',
    },
    {
      id: 3261,
      user_id: 1721,
      plant_id: 2,
      date: '2016-11-11',
      area: 50,
      unit: 'm2',
      desc: '',
      province: 0,
      city: 0,
      subdistrict: 0,
      village: 0,
      foto: null,
      foto_thumb: null,
      cropping_system: 'Polybag',
      seed_id: null,
      watering: null,
      type_land: null,
      fertility: null,
      using_persemian: null,
      height_land: 'sedang',
      longitude: '-6.2572095',
      latitude: '106.6186657',
      created_at: '2016-11-11 11:41:24',
      updated_at: '2016-11-11 12:06:20',
      plant_category_id: 7,
      plant_varieties_id: 245,
      status: '1',
      soil_ph: '6,5-7',
      plant_fase: 'Persemaian',
      plant_address_gps: 'Curug Sangereng Kelapa Dua Banten Indonesia Indonesia null',
      is_temporary_variety: false,
      temp_fase: null,
      type: null,
      plant_category_name: 'Merah Besar',
      plant_varieties_name: 'Hot Chilli F1',
      province_name: null,
      city_name: null,
      subdistrict_name: null,
      village_name: null,
      plant_name: 'Cabai',
      seed_name: null,
      disclaimer: 'Data merupakan estimasi',
      age_plant: '0 hari',
      estimate: '01 January 1970',
      potential: '0.095 ton',
      reaction: 'Netral',
      dolomit: '0',
    },
    {
      id: 3011,
      user_id: 1721,
      plant_id: 1,
      date: '2016-11-03',
      area: 1000,
      unit: 'm2',
      desc: 'Testing',
      province: 0,
      city: 0,
      subdistrict: 0,
      village: 0,
      foto: null,
      foto_thumb: null,
      cropping_system: 'PTT',
      seed_id: null,
      watering: null,
      type_land: null,
      fertility: null,
      using_persemian: null,
      height_land: 'rendah',
      longitude: '-6.2568468',
      latitude: '106.6181244',
      created_at: '2016-11-03 10:54:10',
      updated_at: '2016-11-10 14:42:57',
      plant_category_id: 4,
      plant_varieties_id: 114,
      status: '1',
      soil_ph: '6,0',
      plant_fase: 'Persemaian',
      plant_address_gps: 'Jalan Scientia Boulevard Kelapa Dua Banten Indonesia Indonesia 15810',
      is_temporary_variety: false,
      temp_fase: 'Pengolahan Lahan dan Persemaian',
      type: null,
      plant_category_name: 'Padi Hibrida',
      plant_varieties_name: 'Hipa 18 ',
      province_name: null,
      city_name: null,
      subdistrict_name: null,
      village_name: null,
      plant_name: 'Padi',
      seed_name: null,
      disclaimer: 'Data merupakan estimasi',
      age_plant: '8 hari',
      estimate: '01 January 1970',
      potential: '0.9 ton',
      reaction: 'Agak Asam',
      dolomit: '0,8',
    },
    {
      id: 2943,
      user_id: 1721,
      plant_id: 1,
      date: '2016-11-03',
      area: 3000,
      unit: 'm2',
      desc: '',
      province: 11,
      city: 154,
      subdistrict: 1882,
      village: 24845,
      foto: 'http://ingkarsa.com/uploads/qarsa/plants/image1468659864.jpg',
      foto_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1468659864.jpg',
      cropping_system: 'PTT',
      seed_id: null,
      watering: null,
      type_land: null,
      fertility: null,
      using_persemian: null,
      height_land: 'rendah',
      longitude: ' 106.84559899999999',
      latitude: '-6.2087634',
      created_at: '2016-11-01 14:39:10',
      updated_at: '2016-11-03 10:52:48',
      plant_category_id: 1,
      plant_varieties_id: 80,
      status: '1',
      soil_ph: '6,0',
      plant_fase: 'Panen',
      plant_address_gps: 'Jl. Minangkabau No.2, Ps. Manggis, Setia Budi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia',
      is_temporary_variety: false,
      temp_fase: null,
      type: 'example',
      plant_category_name: 'Padi Sawah',
      plant_varieties_name: 'Ciherang',
      province_name: 'Dki Jakarta',
      city_name: 'Kota Jakarta Selatan',
      subdistrict_name: ' Jagakarsa',
      village_name: 'Ciganjur',
      plant_name: 'Padi',
      seed_name: null,
      disclaimer: 'Data merupakan estimasi',
      age_plant: '8 hari',
      estimate: '01 January 1970',
      potential: '2.1 ton',
      reaction: 'Agak Asam',
      dolomit: '0,8',
    },
    {
      id: 2944,
      user_id: 1721,
      plant_id: 2,
      date: '2016-09-26',
      area: 2000,
      unit: 'm2',
      desc: '',
      province: 11,
      city: 154,
      subdistrict: 1882,
      village: 24845,
      foto: 'http://ingkarsa.com/uploads/qarsa/plants/image1468660422.jpg',
      foto_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1468660422.jpg',
      cropping_system: 'Lahan',
      seed_id: null,
      watering: null,
      type_land: null,
      fertility: null,
      using_persemian: null,
      height_land: 'rendah',
      longitude: ' 106.84559899999999',
      latitude: '-6.2087634',
      created_at: '2016-11-01 14:39:10',
      updated_at: '2016-11-01 14:39:10',
      plant_category_id: 5,
      plant_varieties_id: 134,
      status: '1',
      soil_ph: '5,8',
      plant_fase: 'Panen',
      plant_address_gps: 'Jl. Minangkabau No.2, Ps. Manggis, Setia Budi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia',
      is_temporary_variety: false,
      temp_fase: null,
      type: 'example',
      plant_category_name: 'Keriting',
      plant_varieties_name: 'Taro F1',
      province_name: 'Dki Jakarta',
      city_name: 'Kota Jakarta Selatan',
      subdistrict_name: ' Jagakarsa',
      village_name: 'Ciganjur',
      plant_name: 'Cabai',
      seed_name: null,
      disclaimer: 'Data merupakan estimasi',
      age_plant: '1 bulan, 16 hari',
      estimate: '01 January 1970',
      potential: '3.2 ton',
      reaction: 'Agak Asam',
      dolomit: '1,7',
    },
  ],
};

let examplePlantDetail = {
  result: 'sukses',
  message: {
    detail: {
      id: 3263,
      user_id: 1721,
      plant_id: 6,
      date: '2016-11-09',
      area: 500,
      unit: 'm2',
      desc: 'Lelelel',
      province: 16,
      city: 271,
      subdistrict: 4019,
      village: 50135,
      foto: 'http://ingkarsa.com/uploads/qarsa/plants/image1478847424.jpg',
      foto_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1478847424.jpg',
      cropping_system: 'Lahan',
      seed_id: null,
      watering: null,
      type_land: null,
      fertility: null,
      using_persemian: null,
      height_land: 'tinggi',
      longitude: '0',
      latitude: '0',
      created_at: '2016-11-11 12:22:08',
      updated_at: '2016-11-11 13:57:04',
      plant_category_id: 19,
      plant_varieties_id: 799,
      status: '1',
      soil_ph: '7,5-8,5',
      plant_fase: 'Pengolahan Lahan',
      plant_address_gps: 'Tidak bisa mendeteksi lokasi',
      is_temporary_variety: false,
      temp_fase: null,
      type: null,
      plant_category_name: 'Kentang',
      plant_varieties_name: 'Medians',
      seed_name: null,
      disclaimer: 'Data merupakan estimasi',
      province_name: 'Banten',
      city_name: 'Kota Tangerang Selatan',
      subdistrict_name: ' Serpong Utara',
      village_name: 'Pakulonan',
      plant_name: 'Kentang',
      plant_system: 29,
      persemaian: false,
    },
    fase: {
      desc: 'Pengolahan Lahan',
      suggest: [
        {
          name: '',
          suggest: [
            'Lahan dibajak sedalam 25-30 cm sampai gembur agar perkembangan akar dan umbi optimal. Kemudian tanah dibiarkan 1 minggu sebelum membuat bedengan.',
            'Bedengan dibuat dengan lebar 70 cm (1 jalur tanaman)/ 140 cm (2 jalur tanaman), tinggi 30 cm dan jarak antar bedengan 30 cm.',
            'Di sekeliling petak bedengan dibuat saluran air/ parit sedalam 50 cm dan lebar 50 cm.',
            'Pupuk kandang sebanyak 10-20 ton/ha diberikan pada bedengan sekitar seminggu sebelum tanam, dicampur pada bedengan atau lubang tanam.',
            'Pupuk dasar berupa Urea: 200-300 Kg/Ha, TSP: 25-300 Kg/Ha, KCl: 200-300 Kg/Ha,  ZA: 300-400 Kg/Ha, pupuk diberikan diantara bibit kentang sewaktu penanaman.',
            'Penanaman: Jarak tanam 70 cm x 30 cm. Lubang tanam dibuat dengan kedalaman 8-10 cm. Bibit dimasukkan lubang tanam , ditimbun dan ditekan tanah sekitar umbi.',
          ],
          hst: '',
        },
      ],
      time: 'fase persemaian 165 hari lagi',
      persemaian: {
        desc: 'Data tidak ada',
        suggest: [
          {
            name: 'Data tidak ada',
            suggest: [],
            hst: 'Data tidak ada',
          },
        ],
        time: 'Data tidak ada',
      },
    },
    estimates: '18 July 2017',
    potential: 1.25,
  },
};

let examplePlantingInformation = {
  result: 'sukses',
  message: {
    id: 1,
    type_plant_id: 1,
    category_plant_id: 1,
    seed_requirement: '25-50 Kg/Ha',
    manure_requirement: '2 Ton/Ha',
    chemical_requirement: 'Urea: 250 Kg/Ha\nSP36: 100 Kg/Ha\nKCl: 100 Kg/Ha',
    simple_planting: 'Info Umum: Penanaman secara PTT merupakan penanaman yang memaksimalkan jumlah anakan. Budidaya dilakukan dengan tahap persiapan lahan, persemaian, pindah tanam, penyiangan, pemupukan, pengendalian hama dan penyakit, panen serta pasca panen._Jumlah bibit per lubang: 2 -3 bibit._Penanaman: Penanaman dapat menggunakan sistem jarwo 2:1, 4:1._Panen: Umur antara 90-115 hari setelah tanam.',
    land_elevation: '0-650 m dpl',
    temperature: '19 - 23 °C',
    weather: null,
    rainfall: '1500 - 2000 mm/th',
    production_result: '6-8 Ton/Ha',
    pests_diseases: 'Lalat bibit, ganjur, siput murbei/ keong mas, burung, walang sangit, belalang, wereng coklat, wereng daun, penggerek batang, anjing tanah, kepinding tanah, hama putih, hama putih palsu, tikus, blast, hawar daun, tungro, bercak coklat, hawar pelepah, busuk batang, kerdil hampa, kerdil rumput, gosong palsu. ',
    created_at: '2016-05-21 13:02:04',
    updated_at: '2016-05-21 13:02:04',
    plant_crop_id: 1,
  },
};

let examplePlantPhotos = {
  result: 'sukses',
  message: [
    {
      id: 231,
      plants_id: 3263,
      photo: 'http://ingkarsa.com/uploads/qarsa/plants/image1478847004.jpg',
      status: false,
      img_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1478847004.jpg',
      created_at: '2016-11-11 13:50:05',
      updated_at: '2016-11-11 13:50:25',
    },
    {
      id: 232,
      plants_id: 3263,
      photo: 'http://ingkarsa.com/uploads/qarsa/plants/image1478847024.jpg',
      status: false,
      img_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1478847024.jpg',
      created_at: '2016-11-11 13:50:25',
      updated_at: '2016-11-11 13:57:04',
    },
    {
      id: 233,
      plants_id: 3263,
      photo: 'http://ingkarsa.com/uploads/qarsa/plants/image1478847424.jpg',
      status: true,
      img_thumb: 'http://ingkarsa.com/uploads/qarsa/plants/thumbnails/thumb_image1478847424.jpg',
      created_at: '2016-11-11 13:57:04',
      updated_at: '2016-11-11 13:57:04',
    },
  ],
};

describe('Plant Server Response Validator', () => {
  it('should validate response data of plants endpoint', () => {
    expect(validatePlants(examplePlant)).toNotEqual(null);
    expect(validatePlants({foo: 123, bar: '123'})).toEqual(null);
  });

  it('should validate response data of plantDetail endpoint', () => {
    expect(validatePlantDetail(examplePlantDetail)).toNotEqual(null);
    expect(validatePlantDetail({foo: 123, bar: '123'})).toEqual(null);
  });

  it('should validate response data of plantingInformation endpoint', () => {
    expect(validatePlantingInformation(examplePlantingInformation)).toNotEqual(null);
    expect(validatePlantingInformation({foo: 123, bar: '123'})).toEqual(null);
  });

  it('should validate response data of plantGalleries endpoint', () => {
    expect(validatePlantPhotos(examplePlantPhotos)).toNotEqual(null);
    expect(validatePlantPhotos({foo: 123, bar: '123'})).toEqual(null);
  });
});
