// @flow

let {describe, it} = global;

import expect from 'expect';
import {
  validateFamerMediaProductList,
  validateFarmerMediaProductByID,
  validateFarmerMediaProductDetail,
} from '../Product';

let exampleProductList = {
  result: 'sukses',
  message: [
    {
      product_id: 1124,
      highlight: true,
      store_id: '',
      user_id: 314,
      product_name: 'Sabana F1',
      price_min: 0,
      price_max: 0,
      produsen_name: 'Panah Merah',
      produsen_address: null,
      province: '',
      city: null,
      subdistrict: '',
      village: '',
      phone: '',
      active_ingredients: '',
      target_pest: '',
      group: '',
      commodity: '',
      desc: '',
      dose: '',
      usage_procedure: '',
      store_email: '',
      store_owner: '',
      created_at: '2016/08/14 21:48:06',
      updated_at: '2016/10/11 08:05:05',
      longitude: '',
      latitude: '',
      distance: '',
      store_profile_pic: '',
      gallery_id: 28,
      product_photo: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471186086.jpg',
      gallery: {
        message: 'foto ada',
        data: [
          {
            photo: 'http://ingkarsa.com/uploads/qarsa/products/image01471186086.jpg',
            photo_thumb: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471186086.jpg',
            primary: true,
          },
        ],
      },
      rate: '0',
      count_comment: 0,
      new: false,
      popular: false,
    },
    {
      product_id: 1132,
      highlight: true,
      store_id: '',
      user_id: 318,
      product_name: 'P21',
      price_min: 0,
      price_max: 0,
      produsen_name: 'Pioneer ',
      produsen_address: 'PT. DuPont Indonesia - Head Office\r\nBeltway Office Park Building A, 5th floor\r\nJl. Ampera Raya 9-10, Jakarta \r\nIndonesia - 12550\r\nTel:  6221-7802371',
      province: '',
      city: 'Kota Jakarta Selatan',
      subdistrict: '',
      village: '',
      phone: '',
      active_ingredients: '',
      target_pest: '',
      group: '',
      commodity: '',
      desc: '',
      dose: '',
      usage_procedure: '',
      store_email: '',
      store_owner: '',
      created_at: '2016/08/15 08:33:57',
      updated_at: '2016/10/07 13:22:20',
      longitude: '',
      latitude: '',
      distance: '',
      store_profile_pic: '',
      gallery_id: 37,
      product_photo: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471224897.jpg',
      gallery: {
        message: 'foto ada',
        data: [
          {
            photo: 'http://ingkarsa.com/uploads/qarsa/products/image01471224837.jpg',
            photo_thumb: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471224837.jpg',
            primary: false,
          },
          {
            photo: 'http://ingkarsa.com/uploads/qarsa/products/image01471224897.jpg',
            photo_thumb: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471224897.jpg',
            primary: true,
          },
        ],
      },
      rate: '4.5',
      count_comment: 2,
      new: false,
      popular: false,
    },
  ],
};

let exampleProduct1 = {
  result: 'sukses',
  message: 'produk ada',
  data: {
    id: 1163,
    user_id: 387,
    name: null,
    usefulness: null,
    desc: null,
    photo_gallery_id: 70,
    created_at: '2016-09-08 14:31:05',
    updated_at: '2016-10-10 06:22:51',
    product_cat: 'pupuk',
    material: null,
    brand: 'Bionsekta ',
    pesticide: null,
    commodity: '',
    pest: '',
    dose: null,
    procedure: null,
    price_1: 0,
    price_2: 55000,
    view: 1,
    slug: 'bionsekta',
    product_exist_id: null,
    toxix_type: null,
    plant_type_id: null,
    plant_cat_id: null,
    plant_var_id: null,
    seeds_recomendation: null,
    seeds_sprout: null,
    seeds_purity: null,
    seeds_age: null,
    seeds_weight: null,
    seeds_durability: null,
    seeds_potency: null,
    seeds_netto: null,
    fert_composition: 'Azospirillum sp. Rhizobium sp. Pseudomonas sp.',
    fert_group: 'Pupuk Hayati ',
    fert_excellence: 'Mampu mengikat nitrogen bebas sehingga dapat meningkatkan pertumbuhan tanaman dan produktivitas.',
    how_app: '1 saset Bionsekta untuk 10 kg benih, 10 kg benih dibasahi dengan air kemudian diaduk merata dengan 1 saset Bionsekta (pastikan Bionsekta melekat sempurna pada benih). Benih siap tanam.',
    fert_dose: null,
    fert_procedure: null,
    fert_netto: '100 gr/benih ',
    warning: null,
    eq_type_product: null,
    eq_cat_product: null,
    eq_dimention: null,
    eq_weight: null,
    eq_materials: null,
    highlight: false,
    color: 'Putih ',
    purity: '1 saset/10 kg benih ',
    license_number: null,
    classification: 'Organik',
    pesticide_formulations: null,
    pesticide_opt_target: null,
    eq_sni_iso: null,
    packing: null,
    seeds_variety: null,
    product_owner: 'PT. Prima Agro Tech ',
    avatar: 'http://ingkarsa.com/uploads/qarsa/users/image1473315121.jpg',
    avatar_fb: null,
    address: 'Jalan Pluit Raya No. 1 Komplek Mall Pluit Junction No. SH-03 ',
    province_name: 'Dki Jakarta',
    city_name: 'Kota Jakarta Utara',
    product_id: 1163,
    materials: '',
    plant_type_name: '',
    plant_cat_name: '',
    plant_var_name: '',
    gallery: {
      message: 'foto ada',
      data: [
        {
          photo: 'http://ingkarsa.com/uploads/qarsa/products/image01473319865.jpg',
          photo_thumb: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01473319865.jpg',
          primary: true,
        },
      ],
    },
    rating: '4',
    count_reviews: 1,
    reviews: {
      message: 'reviews ada',
      data: [
        {
          id: 22,
          user_id: 351,
          product_id: 1163,
          review: 'Top lah',
          created_at: '2016-09-08 14:45:03',
          updated_at: '2016-09-08 14:45:03',
          rate: '4',
          first_name: 'Santosa',
          avatar: 'http://ingkarsa.com/uploads/qarsa/users/http://ingkarsa.com/uploads/qarsa/users/',
          avatar_fb: null,
          premium: false,
        },
      ],
    },
  },
};

let exampleProduct2 = {
  result: 'sukses',
  message: 'produk ada',
  data: {
    id: 731,
    user_id: 855,
    name: null,
    usefulness: null,
    desc: 'PT. Syngenta Indoesia ',
    photo_gallery_id: null,
    created_at: '2016-05-21 18:28:42',
    updated_at: '2016-10-11 15:35:35',
    product_cat: 'pestisida',
    material: null,
    brand: 'Plenum 50 WG',
    pesticide: 'Insektisida',
    commodity: 'Cabai, Padi',
    pest: 'WERENG COKLAT PADA PADI, WALANG SANGIT PADA PADI, WERENG HIJAU/ WERENG DAUN PADA PADI, KEPINDING TANAH PADA PADI, KUTU DAUN PADA CABAI',
    dose: null,
    procedure: null,
    price_1: null,
    price_2: null,
    view: 0,
    slug: 'plenum-50-wg',
    product_exist_id: null,
    toxix_type: null,
    plant_type_id: null,
    plant_cat_id: null,
    plant_var_id: null,
    seeds_recomendation: null,
    seeds_sprout: null,
    seeds_purity: null,
    seeds_age: null,
    seeds_weight: null,
    seeds_durability: null,
    seeds_potency: null,
    seeds_netto: null,
    fert_composition: null,
    fert_group: null,
    fert_excellence: null,
    how_app: null,
    fert_dose: null,
    fert_procedure: null,
    fert_netto: null,
    warning: null,
    eq_type_product: null,
    eq_cat_product: null,
    eq_dimention: null,
    eq_weight: null,
    eq_materials: null,
    highlight: true,
    color: null,
    purity: null,
    license_number: null,
    classification: null,
    pesticide_formulations: 'Butiran',
    pesticide_opt_target: null,
    eq_sni_iso: null,
    packing: null,
    seeds_variety: null,
    product_owner: 'PT. Syngenta Indonesia',
    avatar: null,
    avatar_fb: null,
    address: 'Perkantoran Hijau Arkadia\r\nJl. TB. Simatupang Kav 88',
    province_name: 'Dki Jakarta',
    city_name: 'Kota Jakarta Selatan',
    product_id: 731,
    materials: 'Pymetrozine',
    plant_type_name: '',
    plant_cat_name: '',
    plant_var_name: '',
    gallery: {
      message: 'foto kosong',
      data: [],
    },
    rating: '0',
    count_reviews: 0,
    reviews: {
      message: 'reviews kosong',
      data: [],
    },
  },
};

let exampleProductDetail1 = {
  result: 'sukses',
  message: 'produk ada',
  data: {
    id: 1163,
    user_id: 387,
    brand: 'Bionsekta ',
    product_cat: 'pupuk',
    price_1: 0,
    price_2: 55000,
    photo_product: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01473319865.jpg',
    product_owner: 'PT. Prima Agro Tech ',
    avatar: 'http://ingkarsa.com/uploads/qarsa/users/image1473315121.jpg',
    avatar_fb: '',
    address: 'Jalan Pluit Raya No. 1 Komplek Mall Pluit Junction No. SH-03 ',
    province_name: 'Dki Jakarta',
    city_name: 'Kota Jakarta Utara',
    gallery: {
      message: 'foto ada',
      data: [
        {
          photo: 'http://ingkarsa.com/uploads/qarsa/products/image01473319865.jpg',
          photo_thumb: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01473319865.jpg',
          primary: true,
        },
      ],
    },
    count_reviews: 1,
    reviews: {
      message: 'reviews ada',
      data: [
        {
          id: 22,
          user_id: 351,
          product_id: 1163,
          review: 'Top lah',
          created_at: '2016-09-08 14:45:03',
          updated_at: '2016-09-08 14:45:03',
          rate: '4',
          first_name: 'Santosa',
          avatar: '',
          avatar_fb: '',
          premium: false,
        },
      ],
    },
    rating: '4',
    status: {
      status: 'guest',
      id_review: '',
      post: '',
      rating: 0,
    },
    pesticide: {
      pesticide_formulations: '',
      pesticide_color: '',
      pesticide_purity: '',
      pesticide_toxix_type: '',
      pesticide_license_number: '',
      pesticide_pesticide: '',
      pesticide_desc: '',
      pesticide_how_app: '',
      pesticide_packing: '',
      pesticide_dose: '',
      pesticide_procedure: '',
      pesticide_commodity: '',
      pesticide_pest: '',
      pesticide_materials: '',
    },
    seeds: {
      seeds_variety: '',
      seeds_recomendation: '',
      seeds_sprout: '',
      seeds_purity: '',
      seeds_license_number: '',
      seeds_age: '',
      seeds_weight: '',
      seeds_durability: '',
      seeds_potency: '',
      seeds_netto: '',
      seeds_plant_type_name: '',
    },
    fertilizer: {
      fert_composition: 'Azospirillum sp. Rhizobium sp. Pseudomonas sp.',
      fert_purity: '1 saset/10 kg benih ',
      fert_classification: 'Organik',
      fert_color: 'Putih ',
      fert_license_number: '',
      fert_group: 'Pupuk Hayati ',
      fert_excellence: 'Mampu mengikat nitrogen bebas sehingga dapat meningkatkan pertumbuhan tanaman dan produktivitas.',
      fert_how_app: '1 saset Bionsekta untuk 10 kg benih, 10 kg benih dibasahi dengan air kemudian diaduk merata dengan 1 saset Bionsekta (pastikan Bionsekta melekat sempurna pada benih). Benih siap tanam.',
      fert_dose: '',
      fert_procedure: '',
      fert_netto: '100 gr/benih ',
      fert_warning: '',
    },
    equipment: {
      eq_sni_iso: '',
      eq_type_product: '',
      eq_classification: '',
      eq_cat_product: '',
      eq_dimention: '',
      eq_how_app: '',
      eq_weight: '',
      eq_materials: '',
      eq_usefulness: '',
      eq_warning: '',
    },
  },
};

let exampleProductDetail2 = {
  result: 'sukses',
  message: 'produk ada',
  data: {
    id: 1127,
    user_id: 319,
    brand: 'SWADESI F1',
    product_cat: 'bibit',
    price_1: 0,
    price_2: 0,
    photo_product: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471191422.jpg',
    product_owner: 'Benih Citra Asia',
    avatar: '',
    avatar_fb: '',
    address: '',
    province_name: '',
    city_name: '',
    gallery: {
      message: 'foto ada',
      data: [
        {
          photo: 'http://ingkarsa.com/uploads/qarsa/products/image01471191422.jpg',
          photo_thumb: 'http://ingkarsa.com/uploads/qarsa/products/thumbnails/thumb_image01471191422.jpg',
          primary: true,
        },
      ],
    },
    count_reviews: 0,
    reviews: {
      message: 'reviews kosong',
      data: [],
    },
    rating: '0',
    status: {
      status: 'guest',
      id_review: '',
      post: '',
      rating: 0,
    },
    pesticide: {
      pesticide_formulations: '',
      pesticide_color: '',
      pesticide_purity: '',
      pesticide_toxix_type: '',
      pesticide_license_number: '',
      pesticide_pesticide: '',
      pesticide_desc: '',
      pesticide_how_app: '',
      pesticide_packing: '',
      pesticide_dose: '',
      pesticide_procedure: '',
      pesticide_commodity: '',
      pesticide_pest: '',
      pesticide_materials: '',
    },
    seeds: {
      seeds_variety: 'Swadesi',
      seeds_recomendation: '300-700',
      seeds_sprout: 90,
      seeds_purity: 'Warna buah 100% merah menyala bentuk buah lonjong dengan pundak lebih lebar, kulit tebal, keras, dan cupat buah kecil sehingga tahan simpan. cocok untuk ekspor dan tahan transportasi jara jauh',
      seeds_license_number: '',
      seeds_age: 90,
      seeds_weight: 160,
      seeds_durability: '',
      seeds_potency: '75',
      seeds_netto: '20',
      seeds_plant_type_name: 'Tomat',
    },
    fertilizer: {
      fert_composition: '',
      fert_purity: '',
      fert_classification: '',
      fert_color: '',
      fert_license_number: '',
      fert_group: '',
      fert_excellence: '',
      fert_how_app: '',
      fert_dose: '',
      fert_procedure: '',
      fert_netto: '',
      fert_warning: '',
    },
    equipment: {
      eq_sni_iso: '',
      eq_type_product: '',
      eq_classification: '',
      eq_cat_product: '',
      eq_dimention: '',
      eq_how_app: '',
      eq_weight: '',
      eq_materials: '',
      eq_usefulness: '',
      eq_warning: '',
    },
  },
};

describe('Farmer Media Product Response Validator', () => {
  it('should validate Farmer Media Product Lists', () => {
    expect(validateFamerMediaProductList(exampleProductList)).toNotEqual(null);
    expect(validateFamerMediaProductList({foo: 123, bar: '123'})).toEqual(null);
  });

  it('should validate Farmer Media Product', () => {
    expect(validateFarmerMediaProductByID(exampleProduct1)).toNotEqual(null);
    expect(validateFarmerMediaProductByID(exampleProduct2)).toNotEqual(null);
    expect(validateFarmerMediaProductByID({foo: 123, bar: '123'})).toEqual(null);
  });

  it('should validate Farmer Media Product Detail', () => {
    expect(validateFarmerMediaProductDetail(exampleProductDetail1)).toNotEqual(null);
    expect(validateFarmerMediaProductDetail(exampleProductDetail2)).toNotEqual(null);
    expect(validateFarmerMediaProductDetail({foo: 123, bar: '123'})).toEqual(null);
  });
});
