const path = {
  home: 'Home',
  myPlants: 'MyPlants',
  myPage: 'MyPage',
  weather: 'Weather',
  farmerMedia: 'FarmerMedia',
  nearbyStore: 'NearbyStore',
  farmerMediaInfo: 'FarmerMediaInfo',
  pest: 'Pest',
  marketPrice: 'MarketPrice',
  news: 'News',
  businessAnalysis: 'BusinessAnalysis',
  notification: 'Notification',
  settings: 'Settings',
  profile: 'Profile',
  myPlantDetail: 'MyPlantDetail',
  seedInfo: 'SeedInfo',
  fertilizerInfo: 'FertilizerInfo',
  pesticideInfo: 'PesticideInfo',
  toolsInfo: 'ToolsInfo',
  machineInfo: 'MachineInfo',
  editProfile: 'EditProfile',
  aboutUs: 'AboutUs',
  contactUs: 'ContactUs',
  addPlant: 'AddPlant',
  seedProducts: 'SeedProducts',
  fertilizerProducts: 'FertilizerProducts',
  pesticideProducts: 'PesticideProducts',
  toolsProduct: 'ToolsProducts',
};

export default path;
